### ISSUE TITLE
Support automatic rebuild of modules

### ISSUE THREAD

**Issue by dewey** [linuxserver/docker-znc#29]
Hey,

I'd prefer to use the linuxserver image over the official one because they don't properly map the user IDs (and also have no intent on changing that). One feature that's really neat about the official one is that it rebuilds modules when you restart the container:

https://github.com/znc/znc-docker/blob/master/full/30-build-modules.sh

Would that be something you'd consider adding in this one too? It makes it very easy for people to just drop in the modules they want and they get rebuilt for the correct version without the need to add all of them to the LS image like right now (https://github.com/linuxserver/docker-znc/pull/23)

Thanks!

**Comment by thelamer** [comment]
How do you propose we handle this? 
It sounds like you have a grasp on this, the logic could be an if statement that looks for a modules folder and installs build dependencies, then builds and moves the output to `/usr/share/znc/modules`. 

Are you interested in loop testing and creating a PR for something like this?

**Comment by dewey** [comment]
I'm not sure what's the best way of doing it in this case. From my understanding it's  downloading the hardcoded modules, putting them into `/tmp/znc/modules` and then running `make` in `/tmp/znc` to build all of that. I usually always did it with `znc-buildmod` but I guess make also includes building the modules folder.

Maybe the steps would be:

1) In https://github.com/linuxserver/docker-znc/blob/master/Dockerfile#L28 we do:

```
mkdir -p \
	/tmp/znc/modules
```

2) We could just `COPY` the content of `/znc-config/modules` to `/tmp/znc/modules`

3) It'll download the default modules via curl like right now

4) Everything will be built here as usual https://github.com/linuxserver/docker-znc/blob/master/Dockerfile#L77

I'll have to give it a try and if that works will open a MR. Let me know if you see any obvious mistakes.

**Comment by thelamer** [comment]
Optimally it would go as follows:

1. If statement for does /config/modules directory exist
2. If statement are build tools installed ? if not run apk commands to install them in container
3. Build array of cpp files using `find` in the /config/modules directory ($MODULES)
4. ensure $MODULES array is not empty
5. Build array of cpp files using `find` in the  /usr/share/znc/modules directory ($INSTALLED)
6. For loop through the array of new modules (for MODULE in $MODULES; do ...)
7. If statement in loop should compare the basename of the cpp file to the whole array of installed cpp files ( if [[ "$(basename "$MODULE")" != *"$INSTALLED"* ]]; then )
8. run znc-buildmod and copy the directory to `/usr/share/znc/modules`

On subsequent runs it should see that the module was already built and copied inside the container. If the user upgrades the container they will be rebuilt and copied. If it has already installed a module it will not do it again. 

Let me know if any of this does not make sense.

**Comment by CHBMB** [comment]
@dewey Any feedback on this?

**Comment by dewey** [comment]
@CHBMB I think it's would be a good strategy of doing it. Unfortunately I didn't have time to look at it myself yet and I always have it on my list. If someone else wants to go ahead with it that would be great but otherwise I'll see what I can do at some point.

**Comment by CHBMB** [comment]
@dewey We'll wait for you, nobody else has requested it, so I guess it's not a pressing change.

**Comment by mattberther** [comment]
Something like https://github.com/linuxserver/docker-znc/pull/16 ?

**Comment by DarthGandalf** [comment]
> (and also have no intent on changing that)

@dewey Could you explain? Did fix of https://github.com/znc/znc-docker/issues/20 not work for you?

**Comment by dewey** [comment]
@DarthGandalf Sorry I don't remember that any more, that was a while ago and I'm currently not running ZNC :(
