### ISSUE TITLE
Add support for identd/oidentd

### ISSUE THREAD

**Issue by vogelfreiheit** [linuxserver/docker-znc#32]
Add oidentd to the image and possibility to open the identd port to the container. This allows the identd module to operate correctly and oidentd can gracefully drop privileges.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by DarthGandalf** [comment]
FTR, here's a similar issue for the official image: https://github.com/znc/znc-docker/issues/9
