### ISSUE TITLE
Include Fish.so module in docker

### ISSUE THREAD

**Issue by Stiefmeister** [linuxserver/docker-znc#35]
Would be great if you could add Fish module [https://wiki.znc.in/Fish] to standard modules.
Many IRC channels still encrypt via ECB logic supported by Fish. 
Integrated Crypt module only supports CBC encryption.

Thanks a lot!

Attached the compiled fish.so to be added to "/usr/lib/znc/"

**Comment by drizuid** [comment]
this is pretty insecure, just look at the security considerations section of your link. I would say, if you want something like this, you should do it yourself. Personally, I would not feel comfortable including something like this in our image. 
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by Stiefmeister** [comment]
Understood, thanks
