### ISSUE TITLE
Add support for /Add module Clientbuffer

### ISSUE THREAD

**Issue by delize** [linuxserver/docker-znc#38]
Desired Behavior:

https://wiki.znc.in/Clientbuffer
https://github.com/CyberShadow/znc-clientbuffer

On a lesser priority, adding any of the other external/third-party modules as well: https://wiki.znc.in/Category:External_Modules

Current Behavior
While I can manually place the plugin in the necessary folder, `docker exec -it znc bash` and then run the necessary commands, it would be nicer if these were either docker-mods or just inherently added into the znc docker image.

Alternative Behavior:
I noticed that Linuxserver's docker build for znc does not support/provide for rolling updates on as described in #29. This way, you could just drop modules in to a folder, and have them automatically build, rather than adding support for each.

**Comment by delize** [comment]
Alternatively, open up the ability for end-users to build custom modules within the docker container. 

When attempting to do this:

```
root@e3511eee33ec:/# znc-buildmod /usr/lib/znc/custom/clientbuffer.cpp
[ !! ] Could not find g++. What happened to your compiler?
```

**Comment by tobbenb** [comment]
There is nothing stopping you in making those docker-mods and PR it to our docker-mod repo.

Building modules in the container are not something we want to support. The build tools are usually massive and will grow the image size a lot.

**Comment by delize** [comment]
Agreed and understood about the build tools causing inflation in size. However, docker-mods seem like an inflated way to drop any custom znc module into the znc program and getting it to work. Docker mods would be one off for each module. 

Performing the function in Issue #29 would render the need to create a docker mod, unneeded. I am still trying to understand the concept of Linuxserver's docker-mod system to make the necessary option.

**Comment by tobbenb** [comment]
As I have no idea how the znc modules build works, I can't comment on the function of the issue you mention, other than it didn't look like there was a final solution.

**Comment by delize** [comment]
I've switched to the znc official docker container - as the benefits of having the build process work, outweigh the con of having the inflated image.
