### ISSUE TITLE
Add support for pointing to SSL certificate files through env vars

### ISSUE THREAD

**Issue by d3adb5** [linuxserver/docker-znc#40]
## Desired Behavior

Setting environment variables such as `CERT_KEY` pointing to the location of an SSL certificate private key should append the relevant lines to the ZNC configuration.

## Current Behavior

There is no way to point ZNC to SSL certificate files without manually editing the ZNC configuration file.

## Alternatives Considered

Manual intervention, which works, but it would be more interesting to have some minimal configuration be possible directly through the Compose file. This way a fresh new ZNC could come up already pointing to the right SSL certificates.

While it's possible to connect to the web interface through SSL on a fresh install if you use a properly configured web server such as NGINX as a proxy, there's no way to point ZNC to your SSL certificate files through the `webadmin` module (at least as far as I know).

**Comment by drizuid** [comment]
We have no plans to introduce additional envvars. it's only 2 lines to edit, you can use the certs from a reverse proxy (like SWAG) and simply map those certs into znc (this is what I do)

**Comment by Maxattax97** [comment]
@drizuid I am trying to set up my ZNC as you have suggested by sharing the SWAG certs with ZNC via a file mapping (volume mount). Can you show an example of how you did it?
