### ISSUE TITLE
[FEAT] Nightly builds

### ISSUE THREAD

**Issue by BakasuraRCE** [linuxserver/docker-znc#45]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It would be great to have images with the latest changes from the main branch

### Reason for change

The versions of the ZNC project have been stuck at 1.8.2 for the past 3 years, however, the main branch is still active up to this day

**Comment by BakasuraRCE** [comment]
hello?

**Comment by drizuid** [comment]
PRs are welcome!

**Comment by aptalca** [comment]
Upstream tagged 1.9.0-rc1, so it seems a new stable release is imminent.

We have no plans to do nightly builds at this time. If upstream is really active and relatively stable in between stable releases, you can perhaps encourage the upstream dev to cut releases more frequently and our ci will pick them up.
