### ISSUE TITLE
Unable to access web interface -- Connection refused.

### ISSUE THREAD

**Issue by JigSawFr** [linuxserver/docker-znc#5]
**Hello !**
I've just setup this ZNC container,
But if in bind it to 6501 default port or another,
I'm unable to access to web interface, access is refused.
I'm using seven other docker images from linuxserver without problems :)
**Thanks you for your amazing work !**

**Comment by sparklyballs** [comment]
it's https

**Comment by JigSawFr** [comment]
@sparklyballs mea cupa, old config with another port inside ! :+1:
