### ISSUE TITLE
Unusable due to bugs on network adding step. Problem getting latest version ?

### ISSUE THREAD

**Issue by JigSawFr** [linuxserver/docker-znc#6]
Hey @sparklyballs 
At moment, if you run a fresh install of this container,
It's unusable because it's impossible to create a network in ZNC.
`Network name is a required argument`
It's a known bug and fixed. But ZNC remain on `10785ee` commit.

Many commits exist after, and one fix this problem :)

Thanks

**Comment by JigSawFr** [comment]
Humm it seems that ZNC strap is not updated:

https://github.com/ProjectFirrre/zncstrap/commit/0ce56c324964a5a788a3a5e0716564e9b6fde0c9

I checked this commit and fix is not present in container.

**Comment by JigSawFr** [comment]
An HOT-fix is not replace by this line directly in container
https://github.com/ProjectFirrre/zncstrap/blob/dev/modules/webadmin/tmpl/add_edit_network.tmpl#L32

**Comment by sparklyballs** [comment]
or ditch bootstrap altogether, i'll make no bones about it, i never liked that thing.

**Comment by lonix** [comment]
Closed by #7

**Comment by JigSawFr** [comment]
In my mind, removing it is not a solution, it's a regression.
But in fact, it's working without need to apply an hotfix.
I will fork this docker image and try to fix it, and add OTR plugin to ZNC.
If it's working i will make a PR ;)

**Comment by sparklyballs** [comment]
it's absolutely a solution , lets call the bootstrap what it is, a plugin.

if the plugin needs patching to work, then it's no longer viable.

**Comment by JigSawFr** [comment]
@sparklyballs i will fix it right on plugin repo
