### ISSUE TITLE
Not on Docker Hub

### ISSUE THREAD

**Issue by sachse** [linuxserver/docker-znc#9]
I can't find your ZNC container on Docker Hub, is that on purpose?

**Comment by sparklyballs** [comment]
https://hub.docker.com/r/lsiodev/znc/

**Comment by sielickin** [comment]
Above link is now 404'ing

**Comment by sparklyballs** [comment]
it's been moved into our main repository since this issue was raised.

consult this list

http://tools.linuxserver.io/dockers

**Comment by sielickin** [comment]
D'oh, now I see the buttons in the readme. Sorry for the trouble.

Thank you for making proper Docker images. 22MB!
